### ISSUE TITLE
Conflict with autoboot.txt from PINN

### ISSUE THREAD

**Issue by thegigibeast** [matthuisman/plugin.program.noobs.companion#1]
I am building a Retropie / LibreELEC dual boot Raspberry Pi using PINN, and I wanted to remove the Recovery Mode Screen (on boot when it says Shift can be pressed to enter recovery mode). I followed the instructions from PINN (added the autoboot.txt file at the root of the RECOVERY partition), and when I boot everything is fine, it boots directly into LibreELEC.

The problem is when I try to boot Retropie from within KODI (from the favorite section that has been created by the addon), it now simply reboots LibreELEC and won't boot KODI.

Any clues on how to fix this?

**Comment by matthuisman** [comment]
It's an issue with autoboot.txt / NOOBS
https://github.com/raspberrypi/noobs/issues/390

**Comment by matthuisman** [comment]
Hi @thegigibeast ,

It's an issue with autoboot.txt / NOOBS 
https://github.com/raspberrypi/noobs/issues/390

Each OS needs to be updated to support it if I recall correctly.
So, you could try a LibreELEC 9 beta build and see if that works with autoboot.
But then Lakka may not support it (and therefore can't boot back to KODI)

I used to have an option for NOOBS companion to create / edit the autoboot.txt file.
But due to above issue, I removed it until it's fixed. 
For some older OS's, it would stop the Pi booting altogether!
I instead use the PINN default boot as this is done in software so always works

**Comment by thegigibeast** [comment]
Thanks for the quick answer! If it ever gets corrected and you can add that feature again, it could be great!

**Comment by procount** [comment]
> I instead use the PINN default boot as this is done in software so always works

I tend to agree. Sticky boot is the next best thing. 
I have a feeling that it's not the same issue and that autoboot.txt is taking precedence.

**Comment by matthuisman** [comment]
@thegigibeast

For now, I suggest you remove the autoboot.txt and use my add-on to "Set default boot".
This will setup PINNs sticky_boot & default_partition_to_boot

**Comment by thegigibeast** [comment]
When I add the autoboot.txt file and power on my Pi, it boots directly into LibreELEC (which I have set to be default boot with your addon) and I don't see PINN screens. When I try to boot Retropie from within LibreELEC (from the favorites), the only thing it does is reboot straight into LibreELEC, like if the autoboot.txt file was taking precedence.

When I remove the autoboot.txt file and power on my Pi, I see the PINN screens momentarily, which gives me the opportunity to press shift to enter recovery mode. Except from that, everything works fine, and I can boot to Retropie from LibreELEC using the favorites link created by your addon. The thing is, I don't want to see PINN screens at all.


So, I can confirm that when I remove the autoboot.txt file, KODI boots to Retropie without issue and bypasses PINN screens. But I would also like to be able to bypass PINN screens when I power on my Pi, but when I add the autoboot.txt file to do so, KODI will only reboot instead of booting Retropie.

**Comment by matthuisman** [comment]
@thegigibeast

Thanks. 

One last thing to test, could you please change the autoboot to point to RetroPie instead of LibreELEC.
Then test if it works (autoboots into RetroPie)

**Comment by thegigibeast** [comment]
@matthuisman have you been able to reproduce what I described?

**Comment by matthuisman** [comment]
@thegigibeast 
I'll try confirm today that it isn't anything in my add-on.
Are you just using latest stable LibreELEC 8.2.5?

**Comment by procount** [comment]
Even if confirmed, the fix would be part of the firmware that we have no control over.

**Comment by matthuisman** [comment]
@thegigibeast 
I have confirmed the bug and opened up a new issue over on the NOOBS repo:
https://github.com/raspberrypi/noobs/issues/508
