### ISSUE TITLE
Unable to install bootback with target partition on an usb drive

### ISSUE THREAD

**Issue by iffer** [matthuisman/plugin.program.noobs.companion#3]
Hi,
recently I reinstalled retropie on an usb drive, while PINN is still on the SD card. When I tried to reinstall the bootback option, the noobs companion was unable to install the bootback entry to retropie, because it cannot mount the partition of the retropie installation. 

The error message stated, that the partition "PARTUUID=00037985-06" could not be mounted, so I digged around on the SETTINGS partition of PINN and found the installed_os.json file with the partitions field:

{
  "bootable" : true,
  "description" : "Retropie2 v4.4 gaming distro using Emulation Station for RPi2/3",
  "folder" : "/settings/os/Retropie2",
  "group" : "Games",
  "icon" : "/settings/os/Retropie2/icon.png",
  "name" : "Retropie2",
  "partitions" : [
"/dev/mmcblk0p6",
"PARTUUID=00037985-06"
  ],

After changing the partition entry to '/dev/sda6' and resetting the configuration cache of NOOBS.COMPANION, the installation ran successful.

**Comment by matthuisman** [comment]
Thanks
Fixed in version 0.5.9
https://github.com/matthuisman/plugin.program.noobs.companion/commit/5562af238469ac5415ea41afb90df149a68e4557
